name: build

on:
  pull_request:
    branches: [ remove-dapper ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker build -t rancher/rke .

